### ISSUE TITLE
streaming stopped, reason not-negotiated (-4)

### ISSUE THREAD

**Issue by liaoweiguo** [NVIDIA-AI-IOT/deepstream_python_apps#1]
deepstream_test_2 fail

python -m pdb deepstream_test_2.py streams/sample_1080p_h264.mp4

jetson nano

**Comment by nv-zhliu** [comment]
Please try an H264 elementary stream such as streams/sample_720p.h264. Or try deepstream_test_3.py instead because that app supports mp4 container.

**Comment by nv-zhliu** [comment]
It's best to report issues on the [Deepstream SDK Forums](https://devtalk.nvidia.com/default/board/209). Closing this issue here.
